networks:
  default:
    name: labnet
    external: true

services:
    homeserver:
        image: matrixconduit/matrix-conduit:latest
        container_name: conduit
        restart: unless-stopped
        ports:
          - 8448:8448
        volumes:
            - /opt/conduit/db:/var/lib/matrix-conduit/
        environment:
            CONDUIT_SERVER_NAME: cy7.sh
            CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
            CONDUIT_DATABASE_BACKEND: rocksdb
            CONDUIT_PORT: 8448
            CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
            CONDUIT_ALLOW_REGISTRATION: 'false'
            CONDUIT_ALLOW_FEDERATION: 'true'
            CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
            CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
            #CONDUIT_MAX_CONCURRENT_REQUESTS: 100
            CONDUIT_ADDRESS: 0.0.0.0
            CONDUIT_CONFIG: '' # Ignore this
