networks:
  default:
    name: labnet
    driver: bridge

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:8
    container_name: forgejo
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:2222:22
    environment:
      USER_UID: 1001
      USER_GID: 100
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: host.docker.internal:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: forgejo
    volumes:
      - /opt/forgejo/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh:/data/git/.ssh
    extra_hosts:
      - "host.docker.internal:host-gateway"

  linkding:
    build:
      context: ./linkding
    container_name: linkding
    restart: unless-stopped
    ports:
      - 9090:9090
    environment:
      LD_LOG_X_FORWARDED_FOR: True
      LD_DB_ENGINE: postgres
      LD_DB_PASSWORD: linkding
      LD_DB_HOST: host.docker.internal
    volumes:
      - /opt/linkding:/etc/linkding/data
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    extra_hosts:
      - "host.docker.internal:host-gateway"

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      TZ: America/Toronto
      SERVER_DNS: rss.cy7.sh
    volumes:
      - /opt/freshrss/data:/var/www/FreshRSS/data
      - /opt/freshrss/extensions:/var/www/FreshRSS/extensions
    extra_hosts:
      - "host.docker.internal:host-gateway"

  vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      DOMAIN: "https://pass.cy.sh"
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      LOG_FILE: /data/vaultwarden.log
      TZ: America/Toronto
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: ${PUSH_INSTALLATION_ID}
      PUSH_INSTALLATION_KEY: ${PUSH_INSTALLATION_KEY}
    volumes:
      - /vw-data:/data
