networks:
  default:
    name: labnet
    driver: bridge

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:8
    container_name: forgejo
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      USER_UID: 1000
      USER_GID: 1000
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: host.docker.internal:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: forgejo
    volumes:
      - /opt/forgejo/:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  linkding:
    build:
      context: ./linkding
    container_name: linkding
    restart: unless-stopped
    ports:
      - 9090:9090
    environment:
      LD_LOG_X_FORWARDED_FOR: True
      LD_DB_ENGINE: postgres
      LD_DB_PASSWORD: linkding
      LD_DB_HOST: host.docker.internal
    volumes:
      - /opt/linkding:/etc/linkding/data
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    extra_hosts:
      - "host.docker.internal:host-gateway"

  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      TZ: America/Toronto
      SERVER_DNS: rss.cy7.sh
    volumes:
      - /opt/freshrss/data:/var/www/FreshRSS/data
      - /opt/freshrss/extensions:/var/www/FreshRSS/extensions
    extra_hosts:
      - "host.docker.internal:host-gateway"
